name: Test
'on':
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current latest nginx version
      run: |-
        mapfile -t pklversions < "pkl-versions"
        echo "NGINX_VERSION=$(cat nginx-version)" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        load: true
        tags: test/nginx:latest
        build-args: NGINX_VERSION=${{ env.NGINX_VERSION }}
    - run: |-
        docker network create test-network
        docker run --rm -d --network test-network --name echo hashicorp/http-echo -text="pong"
        docker run --rm -d --network test-network --name nginx -p 8080:80 -e FORWARD_HOST=echo -e FORWARD_PORT=5678 test/nginx:latest

        text=$(curl -s "http://localhost:8080")
        if [[ $text != *"pong"* ]]; then
            echo "Output $text does not contain pong"
            docker stop $(docker ps -q)
            exit 1
        fi

        docker stop $(docker ps -q)
