name: Test
'on':
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get current latest nginx version
      run: echo "NGINX_VERSION=$(cat nginx-version)" >> $GITHUB_ENV
    - name: Build image
      run: docker build --build-arg NGINX_VERSION=${{ env.NGINX_VERSION }} -t test/nginx:latest
    - name: Test image
      run: |-
        docker network create test-network
        docker run --rm -d --network test-network --name echo hashicorp/http-echo -text="pong"
        docker run --rm -d --network test-network --name nginx -p 8080:80 -e FORWARD_HOST=echo -e FORWARD_PORT=5678 test/nginx:latest

        text=$(curl -s "http://localhost:8080")
        docker stop $(docker ps -q)

        if [[ $text != *"pong"* ]]; then
            echo "Output does not contain pong"
            echo "$text"
            exit 1
        else
            echo "$text"
        fi
