name: Update to latest nginx
'on':
  pull_request:
    branches:
    - main
    - develop
  schedule:
  - cron: 0 13 * * 1
  workflow_dispatch: {}
jobs:
  get-current-version:
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ env.NGINX_VERSION }}
      latest-version: ${{ steps.cleaned-tool-release.outputs.release }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get current nginx version
      run: echo "NGINX_VERSION=$(cat nginx-version)" >> $GITHUB_ENV
    - id: tool-release
      name: Get latest nginx version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: nginx
        repo: nginx
        excludes: prerelease, draft
    - id: cleaned-tool-release
      name: Strip leading "release-" from the version string
      run: |-
        latestVersion="${{ steps.tool-release.outputs.release }}"
        echo "release=${latestVersion##*release-}" >> $GITHUB_OUTPUT
    - name: Job Summary
      run: |-
        echo "### Versions" >> $GITHUB_STEP_SUMMARY
        echo "Current version: ${{ env.NGINX_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "Latest version: ${{ steps.cleaned-tool-release.outputs.release }}" >> $GITHUB_STEP_SUMMARY
  update-nginx-version:
    permissions:
      contents: write
      pull-requests: write
    needs:
    - get-current-version
    if: needs.get-current-version.outputs.current-version != needs.get-current-version.outputs.latest-version && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Update nginx-version file with latest release
      run: echo "${{ needs.get-current-version.outputs.latest-version }}" > nginx-version
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: emily-worker/update/${{ needs.get-current-version.outputs.latest-version }}-nginx
        title: Update nginx from ${{ needs.get-current-version.outputs.current-version }} to ${{ needs.get-current-version.outputs.latest-version }}
        assignees: emilymclean
        reviewers: emilymclean
        token: ${{ secrets.WORKER_PAT }}
  keep-alive:
    permissions:
      actions: write
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - uses: liskin/gh-workflow-keepalive@v1
